# 本地环境配置
baseUrl: http://127.0.0.1:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_init?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345

  data:
    redis:
      database: 1
      timeout: 20s
      port: 6379
      host: 127.0.0.1

  rabbitmq:
    host: xxx
    port: 5672
    username: xxx
    password: xxx
  devtools:
    restart:
      enabled: false
ai:
  tongyi:
    appKey: xxx
